// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v2/job/delete": {
            "post": {
                "description": "delete job.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "job"
                ],
                "operationId": "DeleteJobV2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "job id",
                        "name": "job_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteJobRespV2"
                        }
                    }
                }
            }
        },
        "/v2/job/migration": {
            "post": {
                "description": "create or update migration job.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "job"
                ],
                "operationId": "CreateOrUpdateMigrationJobV2",
                "parameters": [
                    {
                        "description": "migration job config",
                        "name": "migration_job_config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrUpdateMysqlToMysqlJobParamV2"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrUpdateMysqlToMysqlJobRespV2"
                        }
                    }
                }
            }
        },
        "/v2/job/migration/detail": {
            "get": {
                "description": "get migration job detail.",
                "tags": [
                    "job"
                ],
                "operationId": "GetMigrationJobDetailV2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "job id",
                        "name": "job_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MysqlToMysqlJobDetailRespV2"
                        }
                    }
                }
            }
        },
        "/v2/job/pause": {
            "post": {
                "description": "pause job.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "job"
                ],
                "operationId": "PauseJobV2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "job id",
                        "name": "job_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PauseJobRespV2"
                        }
                    }
                }
            }
        },
        "/v2/job/resume": {
            "post": {
                "description": "resume job.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "job"
                ],
                "operationId": "ResumeJobV2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "job id",
                        "name": "job_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResumeJobRespV2"
                        }
                    }
                }
            }
        },
        "/v2/job/subscription": {
            "post": {
                "description": "create or update subscription job.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "job"
                ],
                "operationId": "CreateOrUpdateSubscriptionJobV2",
                "parameters": [
                    {
                        "description": "subscription job config",
                        "name": "subscription_job_config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrUpdateMysqlToKafkaJobParamV2"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrUpdateMysqlToKafkaJobRespV2"
                        }
                    }
                }
            }
        },
        "/v2/job/subscription/detail": {
            "get": {
                "description": "get subscription job detail.",
                "tags": [
                    "job"
                ],
                "operationId": "GetSubscriptionJobDetailV2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "job id",
                        "name": "job_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MysqlToKafkaJobDetailRespV2"
                        }
                    }
                }
            }
        },
        "/v2/job/sync": {
            "post": {
                "description": "create or update sync job.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "job"
                ],
                "operationId": "CreateOrUpdateSyncJobV2",
                "parameters": [
                    {
                        "description": "sync job config",
                        "name": "sync_job_config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrUpdateMysqlToMysqlJobParamV2"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CreateOrUpdateMysqlToMysqlJobRespV2"
                        }
                    }
                }
            }
        },
        "/v2/job/sync/detail": {
            "get": {
                "description": "get sync job detail.",
                "tags": [
                    "job"
                ],
                "operationId": "GetSyncJobDetailV2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "job id",
                        "name": "job_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MysqlToMysqlJobDetailRespV2"
                        }
                    }
                }
            }
        },
        "/v2/jobs": {
            "get": {
                "description": "get job list.",
                "tags": [
                    "job"
                ],
                "operationId": "JobListV2",
                "parameters": [
                    {
                        "enum": [
                            "migration",
                            "sync",
                            "subscription"
                        ],
                        "type": "string",
                        "description": "filter job type",
                        "name": "filter_job_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter job id",
                        "name": "filter_job_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter job status",
                        "name": "filter_job_status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "job_create_time"
                        ],
                        "type": "string",
                        "default": "job_create_time",
                        "description": "order by",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter job type",
                        "name": "filter_job_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.JobListRespV2"
                        }
                    }
                }
            }
        },
        "/v2/log/level": {
            "post": {
                "description": "reload log level dynamically.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "log"
                ],
                "operationId": "UpdateLogLevelV2",
                "parameters": [
                    {
                        "enum": [
                            "TRACE",
                            "DEBUG",
                            "INFO",
                            "WARN",
                            "ERROR"
                        ],
                        "type": "string",
                        "description": "dtle log level",
                        "name": "dtle_log_level",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UpdataLogLevelRespV2"
                        }
                    }
                }
            }
        },
        "/v2/monitor/task": {
            "get": {
                "description": "get progress of tasks within an allocation.",
                "tags": [
                    "monitor"
                ],
                "operationId": "GetTaskProgressV2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "allocation id",
                        "name": "allocation_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "task name",
                        "name": "task_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "nomad_http_address is the http address of the nomad that the target dtle is running with. ignore it if you are not sure what to provide",
                        "name": "nomad_http_address",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetTaskProgressRespV2"
                        }
                    }
                }
            }
        },
        "/v2/mysql/columns": {
            "get": {
                "description": "list columns of mysql source instance.",
                "tags": [
                    "mysql"
                ],
                "operationId": "ListMysqlColumnsV2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mysql host",
                        "name": "mysql_host",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql port",
                        "name": "mysql_port",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql user",
                        "name": "mysql_user",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql password",
                        "name": "mysql_password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql schema",
                        "name": "mysql_schema",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql table",
                        "name": "mysql_table",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql character set",
                        "name": "mysql_character_set",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "indecate that mysql password is encrypted or not",
                        "name": "is_mysql_password_encrypted",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ListColumnsRespV2"
                        }
                    }
                }
            }
        },
        "/v2/mysql/schemas": {
            "get": {
                "description": "list schemas of mysql source instance.",
                "tags": [
                    "mysql"
                ],
                "operationId": "ListMysqlSchemasV2",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mysql host",
                        "name": "mysql_host",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql port",
                        "name": "mysql_port",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql user",
                        "name": "mysql_user",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql password",
                        "name": "mysql_password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mysql character set",
                        "name": "mysql_character_set",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "indecate that mysql password is encrypted or not",
                        "name": "is_mysql_password_encrypted",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ListMysqlSchemasRespV2"
                        }
                    }
                }
            }
        },
        "/v2/nodes": {
            "get": {
                "description": "get node list.",
                "tags": [
                    "node"
                ],
                "operationId": "NodeListV2",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.NodeListRespV2"
                        }
                    }
                }
            }
        },
        "/v2/validation/job": {
            "post": {
                "description": "validate job config.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "validation"
                ],
                "operationId": "ValidateJobV2",
                "parameters": [
                    {
                        "description": "validate job config",
                        "name": "job_config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ValidateJobReqV2"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ValidateJobRespV2"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BasicTaskProfile": {
            "type": "object",
            "properties": {
                "configuration": {
                    "$ref": "#/definitions/models.Configuration"
                },
                "connection_info": {
                    "$ref": "#/definitions/models.ConnectionInfo"
                },
                "dtle_node_infos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DtleNodeInfo"
                    }
                },
                "job_base_info": {
                    "$ref": "#/definitions/models.JobBaseInfo"
                },
                "replicate_do_db": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MysqlDataSourceConfig"
                    }
                },
                "replicate_ignore_db": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MysqlDataSourceConfig"
                    }
                }
            }
        },
        "models.BinlogValidation": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a string version of any error that may have occured",
                    "type": "string"
                },
                "validated": {
                    "type": "boolean"
                }
            }
        },
        "models.BufferStat": {
            "type": "object",
            "properties": {
                "applier_tx_queue_size": {
                    "type": "integer"
                },
                "binlog_event_queue_size": {
                    "type": "integer"
                },
                "extractor_tx_queue_size": {
                    "type": "integer"
                },
                "send_by_size_full": {
                    "type": "integer"
                },
                "send_by_timeout": {
                    "type": "integer"
                }
            }
        },
        "models.Configuration": {
            "type": "object",
            "properties": {
                "binlog_relay": {
                    "type": "boolean"
                },
                "chunk_size": {
                    "type": "integer"
                },
                "fail_over": {
                    "type": "boolean"
                },
                "group_max_size": {
                    "type": "integer"
                },
                "group_timeout": {
                    "type": "integer"
                },
                "parallel_workers": {
                    "type": "integer"
                },
                "repl_chan_buffer_size": {
                    "type": "integer"
                },
                "retry_time": {
                    "type": "integer"
                }
            }
        },
        "models.ConnectionInfo": {
            "type": "object",
            "properties": {
                "dst_data_base_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MysqlConnectionConfig"
                    }
                },
                "src_data_base_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MysqlConnectionConfig"
                    }
                }
            }
        },
        "models.ConnectionValidation": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a string version of any error that may have occured",
                    "type": "string"
                },
                "validated": {
                    "type": "boolean"
                }
            }
        },
        "models.CreateOrUpdateMysqlToKafkaJobParamV2": {
            "type": "object",
            "required": [
                "dest_task",
                "job_id",
                "src_task"
            ],
            "properties": {
                "dest_task": {
                    "$ref": "#/definitions/models.KafkaDestTaskConfig"
                },
                "failover": {
                    "description": "failover default:true",
                    "type": "boolean",
                    "example": true
                },
                "is_mysql_password_encrypted": {
                    "type": "boolean"
                },
                "job_id": {
                    "type": "string"
                },
                "src_task": {
                    "$ref": "#/definitions/models.MysqlSrcTaskConfig"
                },
                "task_step_name": {
                    "type": "string"
                }
            }
        },
        "models.CreateOrUpdateMysqlToKafkaJobRespV2": {
            "type": "object",
            "required": [
                "dest_task",
                "job_id",
                "src_task"
            ],
            "properties": {
                "dest_task": {
                    "$ref": "#/definitions/models.KafkaDestTaskConfig"
                },
                "eval_create_index": {
                    "type": "integer"
                },
                "failover": {
                    "description": "failover default:true",
                    "type": "boolean",
                    "example": true
                },
                "is_mysql_password_encrypted": {
                    "type": "boolean"
                },
                "job_id": {
                    "type": "string"
                },
                "job_modify_index": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "src_task": {
                    "$ref": "#/definitions/models.MysqlSrcTaskConfig"
                },
                "task_step_name": {
                    "type": "string"
                }
            }
        },
        "models.CreateOrUpdateMysqlToMysqlJobParamV2": {
            "type": "object",
            "required": [
                "dest_task",
                "job_id",
                "src_task"
            ],
            "properties": {
                "dest_task": {
                    "$ref": "#/definitions/models.MysqlDestTaskConfig"
                },
                "failover": {
                    "description": "failover default:true",
                    "type": "boolean",
                    "example": true
                },
                "is_mysql_password_encrypted": {
                    "type": "boolean"
                },
                "job_id": {
                    "type": "string"
                },
                "src_task": {
                    "$ref": "#/definitions/models.MysqlSrcTaskConfig"
                },
                "task_step_name": {
                    "type": "string"
                }
            }
        },
        "models.CreateOrUpdateMysqlToMysqlJobRespV2": {
            "type": "object",
            "required": [
                "dest_task",
                "job_id",
                "src_task"
            ],
            "properties": {
                "dest_task": {
                    "$ref": "#/definitions/models.MysqlDestTaskConfig"
                },
                "eval_create_index": {
                    "type": "integer"
                },
                "failover": {
                    "description": "failover default:true",
                    "type": "boolean",
                    "example": true
                },
                "is_mysql_password_encrypted": {
                    "type": "boolean"
                },
                "job_id": {
                    "type": "string"
                },
                "job_modify_index": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "src_task": {
                    "$ref": "#/definitions/models.MysqlSrcTaskConfig"
                },
                "task_step_name": {
                    "type": "string"
                }
            }
        },
        "models.CurrentCoordinates": {
            "type": "object",
            "properties": {
                "file": {
                    "type": "string"
                },
                "gtid_set": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "read_master_log_pos": {
                    "type": "integer"
                },
                "relay_master_log_file": {
                    "type": "string"
                },
                "retrieved_gtid_set": {
                    "type": "string"
                }
            }
        },
        "models.DelayCount": {
            "type": "object",
            "properties": {
                "num": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "models.DeleteJobRespV2": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.DtleNodeInfo": {
            "type": "object",
            "properties": {
                "data_source": {
                    "type": "string"
                },
                "node_addr": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                }
            }
        },
        "models.GetTaskProgressRespV2": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "tasks_status": {
                    "$ref": "#/definitions/models.TaskProgress"
                }
            }
        },
        "models.GtidModeValidation": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a string version of any error that may have occured",
                    "type": "string"
                },
                "validated": {
                    "type": "boolean"
                }
            }
        },
        "models.JobBaseInfo": {
            "type": "object",
            "properties": {
                "delay": {
                    "type": "integer"
                },
                "job_create_time": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "job_status": {
                    "type": "string"
                },
                "job_steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JobStep"
                    }
                },
                "subscription_topic": {
                    "type": "string"
                }
            }
        },
        "models.JobListItemV2": {
            "type": "object",
            "properties": {
                "dst_addr_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "job_create_time": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "job_status": {
                    "type": "string"
                },
                "job_steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JobStep"
                    }
                },
                "src_addr_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "topic": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "models.JobListRespV2": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JobListItemV2"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.JobStep": {
            "type": "object",
            "properties": {
                "job_create_time": {
                    "type": "string"
                },
                "step_name": {
                    "type": "string"
                },
                "step_schedule": {
                    "type": "number"
                },
                "step_status": {
                    "type": "string"
                }
            }
        },
        "models.KafkaDestTaskConfig": {
            "type": "object",
            "required": [
                "kafka_broker_addrs",
                "kafka_topic",
                "task_name"
            ],
            "properties": {
                "kafka_broker_addrs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "127.0.0.1:9092"
                    ]
                },
                "kafka_topic": {
                    "type": "string"
                },
                "message_group_max_size": {
                    "type": "integer"
                },
                "message_group_timeout": {
                    "type": "integer"
                },
                "node_id": {
                    "type": "string"
                },
                "task_name": {
                    "type": "string"
                }
            }
        },
        "models.ListColumnsRespV2": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ListMysqlSchemasRespV2": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "schemas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SchemaItem"
                    }
                }
            }
        },
        "models.MysqlConnectionConfig": {
            "type": "object",
            "required": [
                "mysql_host",
                "mysql_password",
                "mysql_port",
                "mysql_user"
            ],
            "properties": {
                "mysql_host": {
                    "type": "string"
                },
                "mysql_password": {
                    "type": "string"
                },
                "mysql_port": {
                    "type": "integer"
                },
                "mysql_user": {
                    "type": "string"
                }
            }
        },
        "models.MysqlDataSourceConfig": {
            "type": "object",
            "properties": {
                "table_schema": {
                    "type": "string"
                },
                "table_schema_regex": {
                    "type": "string"
                },
                "table_schema_rename": {
                    "type": "string"
                },
                "tables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MysqlTableConfig"
                    }
                }
            }
        },
        "models.MysqlDestTaskConfig": {
            "type": "object",
            "required": [
                "mysql_connection_config",
                "task_name"
            ],
            "properties": {
                "mysql_connection_config": {
                    "$ref": "#/definitions/models.MysqlConnectionConfig"
                },
                "node_id": {
                    "type": "string"
                },
                "parallel_workers": {
                    "type": "integer"
                },
                "task_name": {
                    "type": "string"
                }
            }
        },
        "models.MysqlSrcTaskConfig": {
            "type": "object",
            "required": [
                "mysql_connection_config",
                "task_name"
            ],
            "properties": {
                "binlog_relay": {
                    "type": "boolean"
                },
                "chunk_size": {
                    "type": "integer"
                },
                "drop_table_if_exists": {
                    "type": "boolean"
                },
                "group_max_size": {
                    "type": "integer"
                },
                "group_timeout": {
                    "type": "integer"
                },
                "gtid": {
                    "type": "string"
                },
                "mysql_connection_config": {
                    "$ref": "#/definitions/models.MysqlConnectionConfig"
                },
                "node_id": {
                    "type": "string"
                },
                "repl_chan_buffer_size": {
                    "type": "integer"
                },
                "replicate_do_db": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MysqlDataSourceConfig"
                    }
                },
                "replicate_ignore_db": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MysqlDataSourceConfig"
                    }
                },
                "skip_create_db_table": {
                    "type": "boolean"
                },
                "task_name": {
                    "type": "string"
                }
            }
        },
        "models.MysqlTableConfig": {
            "type": "object",
            "properties": {
                "column_map_from": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "table_name": {
                    "type": "string"
                },
                "table_regex": {
                    "type": "string"
                },
                "table_rename": {
                    "type": "string"
                },
                "where": {
                    "type": "string"
                }
            }
        },
        "models.MysqlTaskValidationReport": {
            "type": "object",
            "properties": {
                "binlog_validation": {
                    "$ref": "#/definitions/models.BinlogValidation"
                },
                "connection_validation": {
                    "$ref": "#/definitions/models.ConnectionValidation"
                },
                "gtid_mode_validation": {
                    "$ref": "#/definitions/models.GtidModeValidation"
                },
                "privileges_validation": {
                    "$ref": "#/definitions/models.PrivilegesValidation"
                },
                "server_id_validation": {
                    "$ref": "#/definitions/models.ServerIDValidation"
                },
                "task_name": {
                    "type": "string"
                }
            }
        },
        "models.MysqlToKafkaJobDetailRespV2": {
            "type": "object",
            "properties": {
                "basic_task_profile": {
                    "$ref": "#/definitions/models.BasicTaskProfile"
                },
                "message": {
                    "type": "string"
                },
                "task_logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TaskLog"
                    }
                }
            }
        },
        "models.MysqlToMysqlJobDetailRespV2": {
            "type": "object",
            "properties": {
                "basic_task_profile": {
                    "$ref": "#/definitions/models.BasicTaskProfile"
                },
                "message": {
                    "type": "string"
                },
                "task_logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TaskLog"
                    }
                }
            }
        },
        "models.NatsMessageStatistics": {
            "type": "object",
            "properties": {
                "in_bytes": {
                    "type": "integer"
                },
                "in_messages": {
                    "type": "integer"
                },
                "out_bytes": {
                    "type": "integer"
                },
                "out_messages": {
                    "type": "integer"
                },
                "reconnects": {
                    "type": "integer"
                }
            }
        },
        "models.NodeListItemV2": {
            "type": "object",
            "properties": {
                "datacenter": {
                    "type": "string"
                },
                "node_address": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "node_name": {
                    "type": "string"
                },
                "node_status": {
                    "type": "string"
                },
                "node_status_description": {
                    "type": "string"
                }
            }
        },
        "models.NodeListRespV2": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NodeListItemV2"
                    }
                }
            }
        },
        "models.PauseJobRespV2": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.PrivilegesValidation": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a string version of any error that may have occured",
                    "type": "string"
                },
                "validated": {
                    "type": "boolean"
                }
            }
        },
        "models.ResumeJobRespV2": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.SchemaItem": {
            "type": "object",
            "properties": {
                "schema_name": {
                    "type": "string"
                },
                "tables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TableItem"
                    }
                }
            }
        },
        "models.ServerIDValidation": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is a string version of any error that may have occured",
                    "type": "string"
                },
                "validated": {
                    "type": "boolean"
                }
            }
        },
        "models.TableItem": {
            "type": "object",
            "properties": {
                "table_name": {
                    "type": "string"
                }
            }
        },
        "models.TaskEvent": {
            "type": "object",
            "properties": {
                "event_type": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "setup_error": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "models.TaskLog": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "allocation_id": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "task_events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TaskEvent"
                    }
                }
            }
        },
        "models.TaskProgress": {
            "type": "object",
            "properties": {
                "ETA": {
                    "type": "string"
                },
                "backlog": {
                    "type": "string"
                },
                "buffer_status": {
                    "$ref": "#/definitions/models.BufferStat"
                },
                "current_coordinates": {
                    "$ref": "#/definitions/models.CurrentCoordinates"
                },
                "delay_count": {
                    "$ref": "#/definitions/models.DelayCount"
                },
                "exec_master_row_count": {
                    "type": "integer"
                },
                "exec_master_tx_count": {
                    "type": "integer"
                },
                "nats_message_status": {
                    "$ref": "#/definitions/models.NatsMessageStatistics"
                },
                "progress_PCT": {
                    "type": "string"
                },
                "read_master_row_count": {
                    "type": "integer"
                },
                "read_master_tx_count": {
                    "type": "integer"
                },
                "stage": {
                    "type": "string"
                },
                "throughput_status": {
                    "$ref": "#/definitions/models.ThroughputStat"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "models.ThroughputStat": {
            "type": "object",
            "properties": {
                "num": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "models.UpdataLogLevelRespV2": {
            "type": "object",
            "properties": {
                "dtle_log_level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ValidateJobReqV2": {
            "type": "object",
            "required": [
                "dest_task",
                "job_id",
                "src_task"
            ],
            "properties": {
                "dest_task": {
                    "$ref": "#/definitions/models.MysqlDestTaskConfig"
                },
                "is_mysql_password_encrypted": {
                    "type": "boolean"
                },
                "job_id": {
                    "type": "string"
                },
                "src_task": {
                    "$ref": "#/definitions/models.MysqlSrcTaskConfig"
                }
            }
        },
        "models.ValidateJobRespV2": {
            "type": "object",
            "properties": {
                "driver_config_validated": {
                    "description": "DriverConfigValidated indicates whether the agent validated the driver",
                    "type": "boolean"
                },
                "job_validation_error": {
                    "type": "string"
                },
                "job_validation_warning": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "mysql_task_validation_report": {
                    "description": "config",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MysqlTaskValidationReport"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
